#!/bin/bash
/usr/bin/aws s3 sync s3://papaand1-58426 /var/www/html/ --profile papa
/bin/touch /var/spool/cron/root
sudo /bin/echo '*/5 * * * * aws s3 sync s3://papaand1-58426 /var/www/html --profile papa' >> /var/spool/cron/root
